#!/bin/bash
set -e  # don't allow errors to fail silently
julia --project=. --threads=auto --startup-file=no --heap-size-hint=500M -e '
using Pkg;
Pkg.add("PrettyTables");
Pkg.add("AlgebraicRewriting");
Pkg.add("Catlab");
exit();
'
